#install apache httpd
---
- name: Playbook for installing httpd
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: start httpd service
    service:
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes #add this line to deal with error handling in playbooks

  - name: install apache2
    apt:
      name: apache2
      state: present #state is optional
    when: ansible_os_family == "Debian"
  - name: start apache2 service
    service:
        name: apache2
        state: started
    when: ansible_os_family == "Debian"

  - name: copy index file
    copy:
       src: /opt/ansible/index.html
       dest: /var/www/html
       mode: 0666
