#removing apache httpd
---
- name: Playbook for uninstalling httpd
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
        name: httpd
        state: stopped
    when: ansible_os_family == "RedHat"
  - name: uninstall httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: stop apahce2
    service:
       name: apache2
       state: stopped
    when: ansible_os_family == "Debian"

  - name: unistall apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
